### ISSUE TITLE
Not related to web content (Packages not working)

### ISSUE THREAD

**Issue by trampas** [gnuarmeclipse/gnuarmeclipse.github.io#3]
I tried to download packages but does not work. Here is the console log:

[...]

**Comment by ilg-ul** [comment]
Excerpt from this tracker READ ME FIRST: "Please use this tracker to record any issues related only to the GNU ARM Eclipse Web site (typos, wrong phrasing, suggestions, etc). "

http://gnuarmeclipse.github.io/plugins/packs-manager/#pack-install
