### ISSUE TITLE
Bug: incorrect link to peripheral-registers

### ISSUE THREAD

**Issue by amosnier** [gnuarmeclipse/gnuarmeclipse.github.io#4]
Hi,
A link called "peripherals registers view" at http://gnuarmeclipse.github.io/plugins/packs-manager/ points back at http://gnuarmeclipse.github.io/plugins/packs-manager/. I believe what was meant was pointing at http://gnuarmeclipse.github.io/debug/peripheral-registers/ instead.

By the way, shouldn't the link called "Web Issues" under support be https://github.com/gnuarmeclipse/gnuarmeclipse.github.io/issues instead of https://github.com/gnuarmeclipse/gnuarmeclipse.github.io/issues/1? I could first not create an issue and it got me confused.

Apart from that, amazing job. It may or may not make me switch from Emacs/Vim + make + gdb to Eclipse. :-)

Best regards,
Alain Mosnier

**Comment by ilg-ul** [comment]
thank you for your message.

I fixed the link to the peripheral registers and to the issues trackers.

>  switch from Emacs/Vim + make + gdb 

"been there, done that" ;-)

I was a hardcore unix terminal users myself, but when I first encountered Eclipse (about 10 years ago?) I decided it is time for a change.
