### ISSUE TITLE
Suggestion: make the peripheral-registers description less restrictive

### ISSUE THREAD

**Issue by amosnier** [gnuarmeclipse/gnuarmeclipse.github.io#5]
The page says:
- double click the GDB SEGGER J-Link Debugging

That seems to restrict the functionality to SEGGER J-Link.

However, I am using openocd, and I can lit and switch off the orange LED on the STM32F4-Discovery by changing the value of GPIOD ODR13 in the GPIOD memory monitor, that I got displayed by selecting GPIOD under "Peripherals" in the Debug perspective.

I'm guessing there is no reason why there would be any restriction in the Peripherals view with openocd, since openocd's GDB server gives access to any memory address, and all peripheral registers are memory mapped. The Peripherals view should just be a mapping of addresses to symbols.

As a side note, GDB should with the right debugging options expose STM32Cube's preprocessor symbols, which could in theory give similar functionality directly from the source code (I haven't tried it), but I still think that this plugin (I am specifically referring to the peripherals view) has a huge added value. We are also using it at my work and my colleagues love it. Who wrote it?

Best regards,
Alain Mosnier

**Comment by ilg-ul** [comment]
> The page says: ...

please provide the url

due to some Eclipse CDT internals, the peripheral view required specific settings in the debugging plug-ins to integrate it. these settings were first implemented in the J-Link plug-in. later they were added to openocd and qemu, but the manual page was not updated.

**Comment by amosnier** [comment]
Hi,

> please provide the url

The page is http://gnuarmeclipse.github.io/debug/peripheral-registers/. Sorry.

> later they were added to openocd and qemu, but the manual page was not updated.

I understand. Thanks for adding openocd support (and QEMU).

Best regards,
Alain Mosnier

**Comment by amosnier** [comment]
> We are also using it at my work and my colleagues love it. Who wrote it?

In all fairness and for the record, I realize now that what we are using at work is not the peripherals view from GNU ARM Eclipse, but another plugin called EmbSysRegView.

GNU ARM Eclipse's seems to work great though.

Best regards,

Alain Mosnier

**Comment by ilg-ul** [comment]
> what we are using at work is not the peripherals view ... but another plugin

any feedback on the reasons of not using the peripherals view and choosing another plug-in?

**Comment by amosnier** [comment]
> any feedback on the reasons of not using the peripherals view and choosing another plug-in?

I have been working on that particular project a little over a year, but it had already been running for several years and inherited its development environment from yet another project using the same MCU. I have not installed the Eclipse plugins myself in that project (we get a pre-configured Eclipse folder), but I don't believe we use GNU ARM Eclipse at all (I will double-check). I'm guessing that when the choices were made, GNU ARM Eclipse was not that mature, so they basically picked other plugins here and there. EmbSysRegView was one of them.

**Comment by ilg-ul** [comment]
> so they basically picked other plugins here and there

ok. and now? did you evaluate the peripherals view? it is available for about one year, already.

**Comment by amosnier** [comment]
> ok. and now? did you evaluate the peripherals view? it is available for about one year, already.

I will mention it to the guy who maintains the development environment but it's not like the solution we have right now is not working (if it ain't broken...). Also, it would probably be better to get all plugins from the same source, but since we have many other plugins that are not related to ARM cross-compiling, GNU ARM Eclipse won't solve the whole problem anyway.

As mentioned, I will double-check whether or not we actually have some plugins from GNU ARM Eclipse already (I'm not entirely sure).

**Comment by ilg-ul** [comment]
> The page is http://gnuarmeclipse.github.io/debug/peripheral-registers/

I fixed the reference to mention other debuggers too.

**Comment by amosnier** [comment]
> ok. and now? did you evaluate the peripherals view? it is available for about one year, already.

I am myself currently evaluating GNU ARM Eclipse for my home projects though. So far so good.
