### ISSUE TITLE
How about a link to the embsysregview project

### ISSUE THREAD

**Issue by RichardLangFromNZ** [gnuarmeclipse/gnuarmeclipse.github.io#7]
http://embsysregview.sourceforge.net/

in the setup instructions on the website, given that it's very relevant to anyone wanting to use Eclipse CDT for embedded development.

thx.

**Comment by ilg-ul** [comment]
how about http://gnuarmeclipse.github.io/debug/peripheral-registers/ ?

**Comment by RichardLangFromNZ** [comment]
Grand, hadn't seen it

thx
