### ISSUE TITLE
Instructions are out of order

### ISSUE THREAD

**Issue by warrencomputes** [gnuarmeclipse/gnuarmeclipse.github.io#8]
Hi.

Near the bottom of page http://gnuarmeclipse.github.io/openocd/install/, there are instructions "Update OpenOCD path" and "OpenOCD Debugging plug-ins".  I believe the order should be reversed.  If you have never installed the plug-ins, then OpenOCD path cannot be updated because it doesn't show up in the Run/Debug pulldown.  I experienced this workflow just today.

Thanks.

**Comment by ilg-ul** [comment]
thank you for the report. please check if the new version is ok.
